a = input("enter a number 1: ")
b = input("enter a number 2: ")
print ("number a is: " , a)
print ("number b is: " , b)
print ("sum is : ", a+b)

x = int(input("enter a number 3: "))
y = int(input("enter a number 4: "))
print ("number x is: " , x)
print ("number y is: " , y)
print ("sum is : ", x+y)
